//..........................................................................................................................
//......................GGGGGGGGGGGGGGG..............................................OOOOOOOOOOOOOOOOO......................
//...................GGGGGGGGGGGGGGGGGGGGGG.......................................OOOOOOOOOOOOOOOOOOOOOOOO..................
//................GGGGGGGGGGGGGGGGGGGGGGGGGGG...................................OOOOOOOOOOOOOOOOOOOOOOOOOOOO................
//..............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..............
//.............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG............................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.............
//...........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.........................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO............
//..........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..........
//.........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.....................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..........
//........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.........
//.......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO........
//.......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.......
//......GGGGGGGGGGGGGGGGGGGGGGG..GGGGGGGGGGGGGGGGGGGGGG...............OOOOOOOOOOOOOOOOOOOOOOO..OOOOOOOOOOOOOOOOOOOOOOO......
//.....GGGGGGGGGGGGGGGGGGG...........GGGGGGGGGGGGGGGGGG..............OOOOOOOOOOOOOOOOOOOO..........OOOOOOOOOOOOOOOOOOO......
//.....GGGGGGGGGGGGGGGGGG..............GGGGGGGGGGGGGGGGG.............OOOOOOOOOOOOOOOOOO..............OOOOOOOOOOOOOOOOOO.....
//....GGGGGGGGGGGGGGGGG.................GGGGGGGGGGGGGGGG............OOOOOOOOOOOOOOOOO.................OOOOOOOOOOOOOOOOO.....
//....GGGGGGGGGGGGGGGG...................GGGGGGGGGGGGGGGG...........OOOOOOOOOOOOOOOO...................OOOOOOOOOOOOOOOOO....
//...GGGGGGGGGGGGGGGG.....................GGGGGGGGGGGGGGG...........OOOOOOOOOOOOOOO.....................OOOOOOOOOOOOOOOO....
//...GGGGGGGGGGGGGGG.......................GGGGGGGGGGGGGG..........OOOOOOOOOOOOOOOO......................OOOOOOOOOOOOOOO....
//..GGGGGGGGGGGGGGGG.......................GGGGGGGGGGGGGG..........OOOOOOOOOOOOOOO........................OOOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGGG.........................GGGGGGGGGGGGG..........OOOOOOOOOOOOOO.........................OOOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGGG.........................GGGGGGGGGGGGG.........OOOOOOOOOOOOOOO..........................OOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGG................................................OOOOOOOOOOOOOOO..........................OOOOOOOOOOOOOO...
//.GGGGGGGGGGGGGGG................................................OOOOOOOOOOOOOO...........................OOOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG.................................................OOOOOOOOOOOOOO............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG.................................................OOOOOOOOOOOOOO............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG.................................................OOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG.................................................OOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG................................................GOOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG.......GOOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG.......GOOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG.......GOOOOOOOOOOOOO..............................OOOOOOOOOOOOO..
//.GGGGGGGGGGGGG................GGGGGGGGGGGGGGGGGGGGGGGGGG.......GOOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG.......GOOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOO.............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOOO............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOOO............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGG...............GGGGGGGGGGGGGGGGGGGGGGGGGG........OOOOOOOOOOOOOO............................OOOOOOOOOOOOOO..
//.GGGGGGGGGGGGGGG...........................GGGGGGGGGGGGG........OOOOOOOOOOOOOO...........................OOOOOOOOOOOOOO...
//.GGGGGGGGGGGGGGG..........................GGGGGGGGGGGGGG........OOOOOOOOOOOOOOO..........................OOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGG..........................GGGGGGGGGGGGGG.........OOOOOOOOOOOOOO.........................OOOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGGG.........................GGGGGGGGGGGGGG.........OOOOOOOOOOOOOOO........................OOOOOOOOOOOOOOO...
//..GGGGGGGGGGGGGGG........................GGGGGGGGGGGGGGG.........OOOOOOOOOOOOOOO.......................OOOOOOOOOOOOOOO....
//..GGGGGGGGGGGGGGGG......................GGGGGGGGGGGGGGGG.........OOOOOOOOOOOOOOOO......................OOOOOOOOOOOOOOO....
//...GGGGGGGGGGGGGGGG.....................GGGGGGGGGGGGGGGG..........OOOOOOOOOOOOOOOO....................OOOOOOOOOOOOOOOO....
//...GGGGGGGGGGGGGGGGG...................GGGGGGGGGGGGGGGGG..........OOOOOOOOOOOOOOOOO..................OOOOOOOOOOOOOOOO.....
//....GGGGGGGGGGGGGGGGG.................GGGGGGGGGGGGGGGGGG...........OOOOOOOOOOOOOOOOO................OOOOOOOOOOOOOOOOO.....
//....GGGGGGGGGGGGGGGGGGG.............GGGGGGGGGGGGGGGGGGGG...........OOOOOOOOOOOOOOOOOO.............OOOOOOOOOOOOOOOOOO......
//.....GGGGGGGGGGGGGGGGGGGG.........GGGGGGGGGGGGGGGGGGGGGG............OOOOOOOOOOOOOOOOOOOO........OOOOOOOOOOOOOOOOOOOO......
//.....GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG............OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.......
//......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.............OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.......
//.......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..............OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO........
//........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.........
//.........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG...............OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO..........
//..........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.GGGGGGGGGGG................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...........
//...........GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG..GGGGGGGGGGG..................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO............
//............GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG....GGGGGGGGGG...................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.............
//..............GGGGGGGGGGGGGGGGGGGGGGGGGGG.....GGGGGGGGGG....................OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO...............
//................GGGGGGGGGGGGGGGGGGGGGGG.......GGGGGGGGGG......................OOOOOOOOOOOOOOOOOOOOOOOOOOO.................
//..................GGGGGGGGGGGGGGGGGGG............................................OOOOOOOOOOOOOOOOOOOOOO...................
//.....................GGGGGGGGGGGG....................................................OOOOOOOOOOOOOO.......................
//..........................................................................................................................
let deck = [];
let selectedCards = ["-", "-", "-", "-", "-", "-"];
let squad = []; // not sure yet if this is gonna be used at all // it's not
let turn = true;
let idonthaveagoodnameforthis = 0;
let animationList = [];
let collectedLoot = false;

let maxHealth = 50;
let health = maxHealth;
let healthOverflow = true;

let maxActions = 1;
let actions = maxActions;
let maxHands = 2;
let hands = maxHands;

let battle = true;
let currentMonster;

let xp = 0;
let money = 0;
let maxShopAttackSlots = 3;
let maxShopMagicSlots = 2;
let maxShopFoodSlots = 1;

let debug = false;
let a;
let b;

function start() {
  if(!debug) {deck.push(rustySword, rustySword, rustySword);} else { deck.push(rustySword, rustySword, rustySword) }
  if (deck.length > 6 && !debug) {
    deck = [rustySword, rustySword, rustySword, rustySword, rustySword, rustySword]
  }
  fullDeck = deck;
  setTimeout(() => {
    enterBattle();
    document.getElementById("title").style.display = "none";
    document.getElementById("battle").style.display = "block";
    document.getElementById("player").style.display = "block";
  }, 300)

  a = window.getComputedStyle(document.getElementById("monster-health-bar"))
  a = a.getPropertyValue("width");
  b = window.getComputedStyle(document.getElementById("monster-health-bar"))
  b = b.getPropertyValue("width");

  if (debug) { document.getElementById("debug").style.display = "block"; }
}